name: Preview

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install and Build 🔧 
        run: |
          cd XCPCIO-Board
          sed -i "s|baidu: ''|baidu: '${{ secrets.BAIDU_ANALYTICS_ID }}'|" config.ts 
          sed -i "s|data_host: '/data/'|data_host: 'https://raw.githubusercontent.com/XCPCIO/XCPCIO-Board-Data/gh-pages/data/'|" config.ts
          cat config.ts
          yarn
          yarn build
          
      - name: Minify HTML Index
        uses: Dup4/minify-html-action@v9
        with:
          src: './XCPCIO-Board/dist/index.html'

      - name: Enable 404.html
        run: |
          cp ./XCPCIO-Board/dist/index.html ./XCPCIO-Board/dist/404.html
          
      - name: Release
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: XCPCIO-Board/dist
          clean: true
          clean-exclude: CNAME
